### ISSUE TITLE
/ becomes : in Atom

### ISSUE THREAD

**Issue by RobynCos** [learn-co-curriculum/ttt-1-welcome-rb#11]
Hi, I'm encountering a problem with Atom.  When I save a new file as "lib/welcome.rb" it changes to "lib:welcome.rb" in treeview and command.  When I run my program as such it works, but fails the test.  I'm not sure what to do but i've been stuck here since yesterday.  Please help.  Thanks!

**Comment by AnnJohn** [comment]
hi @RobynCos apologies for the delay. If this is still an issue could you use the Ask a Question tool in Learn? We use this space specifically for the content in lessons and your problem might either be technical or something specific to you.

Thanks!
