### ISSUE TITLE
the github isn't working

### ISSUE THREAD

**Issue by RUE4FUL** [learn-co-curriculum/ttt-1-welcome-rb#13]
Im struck and can't get my github to work.  can someone please help??

**Comment by nkgt** [comment]
What exactly is your problem? If you give more information someone will try to help you.

**Comment by cjbrock** [comment]
@RUE4FUL If you're still having issues with this lab, please contact our Technical Coaches using the Ask A Question button, and they can work with you to help you figure it out. Thank you! --Corinna
