### ISSUE TITLE
Local Test not running

### ISSUE THREAD

**Issue by mydanni** [learn-co-curriculum/ttt-1-welcome-rb#14]
I have completed this lab but the local test are not updating the learn.co website to show no errors.  It did update for "Learn Submit",

`[01:07:45] (master) ttt-1-welcome-rb-v-000      
// ♥ ruby lib/welcome.rb                        
Welcome to Tic Tac Toe!                         
[01:08:46] (master) ttt-1-welcome-rb-v-000      
// ♥ learn                                      
                                                
lib/welcome.rb                                  
  prints "Welcome to Tic Tac Toe!"              
                                                
Finished in 0.00732 seconds (files took 0.28743 
seconds to load)         `

![2017-03-28_2117](https://cloud.githubusercontent.com/assets/26236203/24434193/15321d3e-13fc-11e7-95b6-abf9ae7d11e5.png)

**Comment by cjbrock** [comment]
@mydanni It appears this is a local issue with the way you are writing the code, not with the lab itself. If you're still having issues with this lab, please contact our Technical Coaches using the Ask A Question button, and they can work with you to help you figure it out.

**Comment by mydanni** [comment]
Hello,

I'm not sure what this message is about. Please let me know. 

Thanks,
Danielle
