### ISSUE TITLE
Spelling mistake in failure message

### ISSUE THREAD

**Issue by sdpmspring** [learn-co-curriculum/ttt-1-welcome-rb#15]
The message should be "Failed Local Tests" instead of "Falled local Tests"
![bug](https://cloud.githubusercontent.com/assets/26786342/25838166/91a5ac78-34b3-11e7-8b68-296509267ca3.PNG)

**Comment by gj** [comment]
Hi @sdpmspring !

It looks like this is an issue with the display of that font on your monitor. Do you have any way of increasing the resolution?
