### ISSUE TITLE
I made a mistake and deleted the file ttt-1-welcome-rb-ruby-intro-000  

### ISSUE THREAD

**Issue by asallem94** [learn-co-curriculum/ttt-1-welcome-rb#16]
I made a mistake and deleted the file ttt-1-welcome-rb-ruby-intro-000. trying to reopen the file does not work how can I fix this issue

**Comment by cjbrock** [comment]
@asallem94 If you're still having issues with this lab, please contact our Technical Coaches using the Ask A Question button, and they can work with you to help you figure it out. Thank you! --Corinna
