### ISSUE TITLE
Readme.md:   redundant example code when expected 2 different examples

### ISSUE THREAD

**Issue by pmknyc** [learn-co-curriculum/ttt-1-welcome-rb#19]
Referring to file: 
learn-co-curriculum/ttt-1-welcome-rb-v-000/readme.md

Text needing correction from this file is pasted below the **** line.
The lecture leads reader to expect 2 different examples of error code but the **same** example shows up twice. I'm not going to suggest a specific edit. I can rerun the lab and produce different error output but some errors I produced might be confusing for some students at this early stage of the course (and I'm a newbie too!). So, it would be great if an instructor or more experienced coder produces new example error code to for 2 distinct examples in the readme file.
 :-)

*************************************************************************

2. Make sure you're printing "Welcome to Tic Tac Toe!" exactly.

When you run `learn` you might see failing tests even though your program seemingly works. The failures might read something like:

```
1) lib/welcome.rb prints "Welcome to Tic Tac Toe!"
   Failure/Error: load './lib/welcome.rb'
     #<IO:0x007fa2b28325a0> received :puts with unexpected arguments
       expected: ("Welcome to Tic Tac Toe!")
            got: ("Welcome to Tic Tac Toe")
   # ./lib/welcome.rb:4:in `puts'
```

Or something that looks like:

```
1) lib/welcome.rb prints "Welcome to Tic Tac Toe!"
   Failure/Error: load './lib/welcome.rb'
     #<IO:0x007fa2b28325a0> received :puts with unexpected arguments
       expected: ("Welcome to Tic Tac Toe!")
            got: ("Welcome to tic tac toe!")
   # ./lib/welcome.rb:4:in `puts'
```

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved. If you do not believe that this issue has been addressed, please re-open this issue. 💙
