### ISSUE TITLE
Better introduction of TicTacToe

### ISSUE THREAD

**Issue by matbalez-zz** [learn-co-curriculum/ttt-1-welcome-rb#2]
Given that building TicTacToe is going to be so central to this whole track, I feel like we should do a better job of teeing that up. Right now it feels almost like a non-sequitur. 

Either with a readme that is dedicated to just introducing that, or a richer introduction that provides more introductory flavor along the lines of:

"One of the things that's most fun about programming is building applications that you can interact with. It's so satisfying to see your code in action! 

Throughout this whole track we'll work together on building your very first app: An interact Tic Tac Toe game. In this lab, we'll get started on laying the foundation for the app. "

etc etc

**Comment by aviflombaum** [comment]
I think this was addressed by providing a generic intro to tic tac toe in the beginning of qualifying.
