### ISSUE TITLE
Not tracking the fork

### ISSUE THREAD

**Issue by MrGametop1** [learn-co-curriculum/ttt-1-welcome-rb#20]
Hello so i have this problem where it dosent track where i am in the process:
Website:
https://gyazo.com/2ae0d1da2363db027abb77d67f279a02
Console in the IDE:
https://gyazo.com/620408d15338a8a5c33ef91665f43985
Code in the file lib/welcome.rb:
https://gyazo.com/58085f80f7211993616982541e2ea50d

**Comment by sgharms** [comment]
Hi there! This request sounds like an improvement to the Learn platform.

Our product team loves to hear about our Learners' innovative interface
improvements. You can reach them at support@learn.co. Alternatively, if Learn
is misbehaving, please direct your bug report to bugs@learn.co.

[Raising issues on GitHub][raise] should be reserved for problems with
the curriculum itself (doesn't work, throws a Ruby error, etc.)

If, on the other hand, we've misunderstood the purpose of this request, please
re-open this issue, provide any additional information you can to clarify our error,
and we will try to find a fix.

[raise]: http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson
