### ISSUE TITLE
Please correct README as follows

### ISSUE THREAD

**Issue by dfsale74** [learn-co-curriculum/ttt-1-welcome-rb#24]
The instructions for this lesson are unclear and should be updated as follows:

1) Contrary to the workflow of the previous lesson, it is NOT necessary to create a new file to contain the 'puts` instruction.  
2) The file `welcome.rb` already exists in the folder `lib' but is not displayed in Learn IDE default view.

**Comment by drakeltheryuujin** [comment]
Hi @dfsale74,

Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.
If you do not believe that this issue has been addressed, please re-open this issue. 💙
