### ISSUE TITLE
IDE not connecting

### ISSUE THREAD

**Issue by iantfleming** [learn-co-curriculum/ttt-1-welcome-rb#31]
When I first downloaded IDE on my desktop, it worked completely fine. Then all of a sudden, it just disconnected and came up with this message: 

Learn IDE: you are not connected!
The connection with the remote server failed.

It has not let me reconnect since. 

Strangely, this issue only occurs on my desktop, and I have got it working on my laptop.

**Comment by lizbur10** [comment]
Closing as outdated
