### ISSUE TITLE
Not clear 

### ISSUE THREAD

**Issue by jacobdwaldman** [learn-co-curriculum/ttt-1-welcome-rb#5]
Instructions are not clear in this program. I tried running learn and then ran a puts for the opening message but I think it is missing an irb statement.

**Comment by AnnJohn** [comment]
Hi @jacobdwaldman thanks for raising the issue. There doesn't need to be anything related to IRB to solve this lab (IRB is a way to test your ruby code via your terminal). But for immediate help with a lab, please use the Ask a Question tool in Learn and someone from our instructor support team will get back to you right away.
