### ISSUE TITLE
SSH

### ISSUE THREAD

**Issue by ktdavis** [learn-co-curriculum/ttt-1-welcome-rb#7]
Getting an error message that Nitrous cannot be opened when I click on the open in Nitrous tab. The error messages asks if I've saved the SSH key. Help please. Thanks!

**Comment by AnnJohn** [comment]
@ktdavis Sorry for the trouble you're having. For immediate help, please use the Ask a Question tool in Learn and someone from our chat support team will get back to you right away. Thanks!
