### ISSUE TITLE
Nitrous wont open for this lab

### ISSUE THREAD

**Issue by mossroad** [learn-co-curriculum/ttt-1-welcome-rb#9]

**Comment by PeterBell** [comment]
Hi @mossroad thanks so much for the feedback - much appreciated. We do have people going through this successfully in nitrous, so I'm going to close this as a general issue, but if you're still having a problem, please use the "Ask a Question" feature to get some individual help/support. Thanks again for taking the time to provide the feedback - very much appreciated!
